// <auto-generated />
namespace JahomWeChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class jahom : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jahom));
        
        string IMigrationMetadata.Id
        {
            get { return "201709180850299_jahom"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
